### ISSUE TITLE
Use uOriginBlock unbreak.txt

### ISSUE THREAD

**Issue by jayvdb** [essandess/easylist-pac-privoxy#4]
https://github.com/uBlockOrigin/uAssets/blob/master/filters/unbreak.txt contains extra rules which unbreak easylist rules.

**Comment by jayvdb** [comment]
This can be achieved with https://github.com/essandess/easylist-pac-privoxy/issues/5 + https://github.com/scrapinghub/adblockparser/issues/13 , and https://github.com/essandess/adblock2privoxy/issues/5

**Comment by essandess** [comment]
Applying `unbreak.txt` rules will not necessarily work to fix `easyprivacy.txt` rules because the existing code presumes that all rules are valid, prioritizes the most relevant ones, then represents these rules in JavaScript hashes or RegExp objects whose execution order is not predefined.

One way to address this is to parse `unbreak.txt` first and not include any breaks rules subsequently.

Another way—my preference—is just to upstream this issue and ask `easyprivacy.txt` to fix their rules.
