### ISSUE TITLE
Banner ads, “Doubleclick” ads still appearing

### ISSUE THREAD

**Issue by jaredbidlow** [essandess/easylist-pac-privoxy#6]
Using the proxy.pac in iOS (Auto config under Wifi name) doesn’t block some ads like the ads.doubleclick ads seen on many popular (and unpopular) websites. It also slows internet connection to certain websites, Twitter for instance.

**Comment by jaredbidlow** [comment]
I should say that the connection is slow all around. it may owe more to the wireless network. I will perform some speed tests with it on and off.

**Comment by essandess** [comment]
@jaredbidlow Please keep these comments in mind as you perform your tests:

1. Only a fraction of easylist rules are included in the `proxy.pac` file because iOS devices don’t have the processing power for the large JavaScript files that would be created from **all** rules. There’s a prioritization algorithm that can be influenced by specifying specific domains or patterns.

2. In my experience, page loading delays are caused by not providing iOS with a working black hole proxy. If you Google around you can see people using various black hole proxies, e.g. [Google DNS](http://blog.monstuff.com/archives/2015/08/ad-blocking-on-ios.html) at `8.8.8.8:53`. This no longer works—iOS wants a functioning web server with a valid return code, or it will sit there and spin until it times out. That’s why the nginx web server in the repo [adblock2privoxy](../../adblock2privoxy) is included as sub-repo here—it provides a functioning black hole for blocked sites. If you can’t hit your black hole yourself with a web browser, iOS will have long delays.
